### ISSUE TITLE
Direct.Request/Responses don't work

### ISSUE THREAD

**Issue by o-alex** [iffyio/kompics-testkit#1]
Direct.Requests need to be triggered from a component so that they get their origin set.
Example failing test:
https://github.com/o-alex/kompics-testkit/tree/master/src/test/java/se/sics/kompics/testkit/directreqresp

**Comment by o-alex** [comment]
Related, issue - Direct.Response shortcuts the path and goes back directly to origin. If you are to monitor events on port, you have to inject yourself(testkit) instead of the true origin and when you get it back, reinject the original origin and pass it through.
@Alex - once the first issue is fixed test - reenable commented expects on LibTFSMDownloadTest1 to test fix on this, second issue.

**Comment by iffyio** [comment]
This issue was moved to kompics/kompics-testing#1
